name: projectm-lobby
main: com.yalcinkaya.lobby.Lobby
version: 1.0
api-version: 1.21
depend: [ DecentHolograms, projectm-core ]

commands:
  spawn:
    description: Return to spawn.
    usage: /<command>
    aliases: [ s ]
  reconnect:
    description: Reconnect to a running match.
    usage: /<command>
    aliases: [ r ]
  party:
    description: Manage your party.
    usage: /<command> [create|invite|join|leave]
    aliases: [ p ]
  elo:
    description: Look up elo stats.
    usage: /elo
    aliases: [ e ]
  setelo:
    description: Set the elo of a player for a specific queue.
    usage: /<command> <playerName> <queueType> <newElo>
  addelo:
    description: Modify the elo of a player for a specific queue.
    usage: /<command> <playerName> <queueType> <eloMod>
  setrank:
    description: Set the rank of a player.
    usage: /<command> <playerName> <rank>
  setsq:
    description: Set Solo Queue team size.
    usage: /<command> <teamSize>
  setpq:
    description: Set Party Queue team size.
    usage: /<command> <teamSize>

